export const USER_TOKEN_KEY = '@USER_TOKEN_KEY';
export const USER_ID_KEY = '@USER_ID_KEY';
export const USER_TOKEN_EXPIRATION_KEY = '@USER_TOKEN_EXPIRATION_KEY';
export const USER_REFRESH_TOKEN_KEY = '@USER_REFRESH_TOKEN_KEY';
