version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn eslint
      - run: yarn run test
      - store_test_results:
          path: ~/project/junit.xml

  android:
    working_directory: ~/project
    docker:
      - image: circleci/android:api-27-node8-alpha
    steps:
      - checkout
      - run: yarn install
      - run: cd android && ./gradlew assembleDebug

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      # - android